DROP TABLE savmaxru_forms_interview;
DROP TABLE savmaxru_forms_question;
DROP TABLE savmaxru_forms_option;
DROP TABLE savmaxru_forms_answer_result;
DROP TABLE savmaxru_forms_answer_to_question;
DROP TABLE savmaxru_forms_answer_option;
DROP TABLE savmaxru_forms_connection_interview_with_question;
DROP TABLE savmaxru_forms_date_info;

